lr = 2e-4
batch_size = 128
seq_len = 20
num_layers = 6
hidden_size = 512
use_weightdecay_nohiddenW = False
decay_factor = 1e-4
opti = 'adam'
pThre = 20
MAG = 5.0
global_test_no = 1
ini_in2hid = 0.002
constrain_U = False
eval_fold = 5
use_bneval = False
ini_b = 0.0
end_rate = 1e-6

n_dimension = 3
num_joints = 50 # two skeletons with each 25 joints
outputclass = 2